#!/bin/sh

#This script will monitor the disk usage and accordingly you can set the cron jobs.

df -H | awk '
    NR == 1 {next}
    $1 == "abc:/xyz/pqr" {next}
    $1 == "tmpfs" {next}
    $1 == "/dev/cdrom" {next}
    1 {sub(/%/,"",$5); print $1, $5} ' | while read filesystem percentage; do

    if [ $percentage -ge 80 ]; then
      mail -s "Alert: Almost out of disk space ($usep%) on $filesystem" "$ADMIN"
    else
        echo "Everything's Fine..!"
    fi

  done

